# usage: ansible-playbook example-playbook.yml --extra-vars="user=ssh_user"
# Variables:
# - module: django_project.wsgi
# - chdir: /home/vagrant/mysite/project_root
# - home: /home/vagrant/mysite/virtualenv

---
- hosts: webservers
  sudo: yes
  vars_files:
    - vars/default.yml
    - [env_specific.yml, vars/default.yml]
  user: ${user}
  tasks:
    - include: tasks/uwsgi.yml
  handlers:
    - include: handlers/uwsgi.yml
